version: "3.8"

services:
  db_users:
    image: postgres:14.4
    container_name: db_users
    restart: always
    ports:
      - 8482:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users
    volumes:
      - pgdata:/data/postgres
  # app_hello_world:
  #   build: .
  #   container_name: app_hello_world
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - 4545:4545
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - db_hello_world
  #   depends_on:
  #     - db_hello_world

volumes:
  pgdata:
    driver: local
